### PR TITLE
HighDimPDE.jl integration

### PR DESCRIPTION
**Pull request by vboussange**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
awesome.

We also need to get it into the SciML/SciMLDocs , but I'll wait on Ashutosh to have a second to complete the docs bit there. He has a busy week ahead of him 😅

**Comment by vboussange** [comment]
What about he tries to fix the tests related to `DeepBSDE` in HighDimPDE.jl, while I do the integration of SciML/SciML docs? I am into documenting today, and will also modify a bit the internal of HighDimPDE.jl to rely upon SciMLBase.jl instead of DiffEqBase.jl :)

**Comment by ChrisRackauckas** [comment]
Sounds good. Yeah. All you really need to do is move `pages` to a separate file like https://github.com/SciML/ModelingToolkit.jl/blob/master/docs/pages.jl because it needs to get that variable so it imports it directly from `docs/pages.jl`. Once that's done, stick it in the list like https://github.com/SciML/SciMLDocs/blob/main/docs/make.jl#L27 and it should be good.

Next though, I want to get those docs on strict mode, which is done like https://github.com/SciML/DiffEqFlux.jl/blob/master/docs/make.jl#L15-L22 and then every code block should be `@example`, then it will be run and if they fail they will throw an error before merging. That will keep the tests good.

We need to also think about what the right home is for:

https://neuralpde.sciml.ai/dev/solvers/kolmogorovbackwards_solver/
https://neuralpde.sciml.ai/dev/examples/kolmogorovbackwards/

https://neuralpde.sciml.ai/dev/solvers/optimal_stopping/
https://neuralpde.sciml.ai/dev/examples/optimal_stopping_american/

Very similar PDE, maybe even a subset of the expanded PDE definition you have in the high dim repo, so maybe they fit right in. But with this change, NeuralPDE is being reconfigured into a package only about physics-informed neural networks (and related bits like physics-informed DeepONets etc.), so those two don't really fit in there.

**Comment by vboussange** [comment]
Ok for the documentation (https://github.com/SciML/SciMLDocs/pull/25). Will do the block codes later on. 

For the Kolmogorov and optimal solvers, they would definitely fit in HighDimPDE.jl and are indeed subsets of the PDE definitions. Should I open an issue to move those two?

**Pull request merged**
